default: &default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: client_offers_api_development

test:
  <<: *default
  database: client_offers_api_test

production:
  <<: *default
  database: client_offers_api_production
  username: client_offers_api
  password: <%= ENV['CLIENT_OFFERS_API_DATABASE_PASSWORD'] %>
